title: Project Portfolio
description: A collection of things I've built and flown.
baseurl: "/projects"
url: "https://spicytenderloin.github.io"

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
    values:
      layout: default
