title: Julian Williams
description: Undergraduate Electrical & Aerospace Engineer
baseurl: ""
url: "https://www.julianw.io"

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
    values:
      layout: default
